### ISSUE TITLE
git_clone macro dont support more than one remote

### ISSUE THREAD

**Issue by renoirb** [webplatform/salt-basesystem#1]
A pillar like this;

``` yml
basesystem:
  salt:
    formulas_repos:
      /srv/formulas/sysctl:
        origin: https://github.com/webplatform/saltstack-sysctl-formula.git
        remotes:
          upstream: git@github.com:webplatform/saltstack-sysctl-formula.git
          author: https://github.com/bechtoldt/saltstack-sysctl-formula.git
```

Would generate sls like that

``` yml
Git clone /srv/formulas/sysctl:
  file.directory:
    - name: /srv/formulas/sysctl
  git.latest:
    - name: https://github.com/webplatform/saltstack-sysctl-formula.git
    - rev: master
    - target: /srv/formulas/sysctl
    - unless: test -d /srv/formulas/sysctl/.git
  cmd.run:
    - name: git remote add author https://github.com/bechtoldt/saltstack-sysctl-formula.git
    - unless: grep -q -e 'remote "author' .git/config
    - cwd: /srv/formulas/sysctl
  cmd.run:
    - name: git remote add upstream git@github.com:webplatform/saltstack-sysctl-formula.git
    - unless: grep -q -e 'remote "upstream' .git/config
    - cwd: /srv/formulas/sysctl
```

In Salt Stack, we can’t have two of the same class (e.g. `cmd`) under the same id (e.g. `Git clone /srv/formulas/sysctl`).
